server:
  port: 9000
 
spring:
  cloud:
    gateway:
      routes:
      - id: userJWTModule
        uri: http://localhost:8081/
        predicates:
        - Path=/user/**
      - id: checklistModule
        uri: http://localhost:8082/
        predicates:
        - Path=/checklist/**- 
      - id: benchmarkModule
        uri: http://localhost:8083/
        predicates:
        - Path=/benchmark/**
      - id: severityModule
        uri: http://localhost:8084/
        predicates:
        - Path=/severity/**
     